# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='labels',
            new_name='label',
        ),
    ]
