# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20180619_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videolabels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_number', models.IntegerField(default=1)),
                ('hidden_status', models.BooleanField(default=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Video')),
            ],
        ),
    ]
