# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_videolabels_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allowed_type',
            field=models.TextField(blank=True, help_text='A JSON blob containing allowed types(which label boxes to be displayed)'),
        ),
    ]
