# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_video_allowed_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='allowed_type',
            new_name='hidden_type',
        ),
    ]
