# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_auto_20180627_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labelset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of class label option.', max_length=100, unique=True)),
                ('color', models.CharField(editable=False, max_length=6)),
                ('class_number', models.IntegerField(default=1)),
                ('label', models.ManyToManyField(blank=True, to='annotator.Label')),
            ],
        ),
    ]
