# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0013_auto_20180629_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelset',
            old_name='description',
            new_name='desc',
        ),
    ]
