# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0014_auto_20180629_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelset',
            name='desc',
        ),
    ]
