# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0015_remove_labelset_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelset',
            name='label',
        ),
        migrations.DeleteModel(
            name='Labelset',
        ),
    ]
