# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0016_auto_20180629_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labelset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of class label option.', max_length=100, unique=True)),
                ('class_number', models.IntegerField(default=1)),
                ('desc', models.CharField(blank=True, help_text='Name of class label option.', max_length=100, unique=True)),
                ('label', models.ManyToManyField(blank=True, to='annotator.Label')),
            ],
        ),
    ]
