# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0017_labelset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelset',
            name='desc',
            field=models.CharField(blank=True, help_text='Name of class label option.', max_length=100),
        ),
    ]
