# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0018_auto_20180629_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='labelset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotator.Labelset'),
            preserve_default=False,
        ),
    ]
