# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0021_auto_20180702_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='labelset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.Labelset'),
        ),
    ]
