# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0023_labellabelset'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.CharField(blank=True, help_text='Date of when the video was created', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of the video file.', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='hidden_type',
            field=models.TextField(blank=True, help_text='A JSON blob containing allowed types(which label bb to be displayed)'),
        ),
    ]
