# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 11:36
from __future__ import unicode_literals

import annotator.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0024_auto_20180801_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='filename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image_list',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='_image_list',
            field=models.TextField(blank=True, db_column='image_list', help_text='List of filenames of images to be used as video frames, in JSON format.When present, image list is assumed and <filename> is ignored.'),
        ),
        migrations.AddField(
            model_name='video',
            name='task_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=annotator.models.unique_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of when the video was added', max_length=100),
        ),
    ]
