# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0029_auto_20190307_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelLabelset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_number', models.IntegerField(default=1)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Label')),
                ('labelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Labelset')),
            ],
        ),
        migrations.CreateModel(
            name='Videolabels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_number', models.IntegerField(default=1)),
                ('hidden_status', models.BooleanField(default=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Label')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='host',
            field=models.CharField(blank=True, help_text='Path to prepend to filenames to form the url for this video or the images in `image_list`.', max_length=1048),
        ),
        migrations.AddField(
            model_name='videolabels',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Video'),
        ),
    ]
