# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0030_auto_20190307_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labellabelset',
            name='label',
        ),
        migrations.RemoveField(
            model_name='labellabelset',
            name='labelset',
        ),
        migrations.RemoveField(
            model_name='videolabels',
            name='label',
        ),
        migrations.RemoveField(
            model_name='videolabels',
            name='video',
        ),
        migrations.DeleteModel(
            name='LabelLabelset',
        ),
        migrations.DeleteModel(
            name='Videolabels',
        ),
    ]
