# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0031_auto_20190307_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='task_id',
        ),
        migrations.AddField(
            model_name='video',
            name='cache_task_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='video',
            name='extract_task_id',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
