# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0031_auto_20190307_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labelset',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='labelmapping',
            old_name='labelset',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='labelset',
            new_name='project',
        ),
    ]
