# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0032_auto_20190315_1651'),
        ('annotator', '0032_auto_20190319_1340'),
    ]

    operations = [
    ]
