# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0033_merge_20190319_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Date of when the video was added', max_length=100),
        ),
    ]
