# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0034_auto_20190320_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='zipfile',
            field=models.FileField(blank=True, upload_to='zipfiles'),
        ),
    ]
