# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0038_auto_20190405_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
